### ISSUE TITLE
Про отношение к коду

### ISSUE THREAD

**Issue by SimePel** [little-programmers/celsius-farenheit-EKBEHTOP#1]
Никогда не пиши код, как будто это шутка или какая-то игра. Код не терпит юмора.

Переменные почти всегда должны иметь смысловые значения, также как и функции. А точнее абсолютно все должно иметь смысл.

Написание кода - это только 1/3 всей работы. В основном ты занимешься чтением кода, отсюда вытекает все то, что сказано выше.

Возьми это на заметку, буду надеяться ты поймешь, почему это так важно!

**Comment by EKBEHTOP** [comment]
Я поняль(
